name: untitled
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_lints: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/vectors/vector_46_x2.svg
    - assets/vectors/vector_9_x2.svg
    - assets/vectors/vector_5_x2.svg
    - assets/vectors/group_1_x2.svg
    - assets/vectors/battery_1_x2.svg
    - assets/vectors/container_x2.svg
    - assets/vectors/cellular_connection_3_x2.svg
    - assets/vectors/vector_37_x2.svg
    - assets/vectors/vector_43_x2.svg
    - assets/vectors/wifi_x2.svg
    - assets/images/pngfuel_8.png
    - assets/images/pngfuel_9.png
    - assets/images/pngfuel_62.png
    - assets/images/pngfuel_6.png
    - assets/images/pngfuel_7.png
    - assets/images/pngfuel.png
    - assets/images/pngfuel_61.png
    - assets/vectors/group_1_x2.svg
    - assets/vectors/vector_51_x2.svg
    - assets/vectors/vector_50_x2.svg
    - assets/vectors/vector_48_x2.svg
    - assets/vectors/vector_27_x2.svg
    - assets/vectors/wifi_4_x2.svg
    - assets/vectors/cellular_connection_5_x2.svg
    - assets/vectors/vector_22_x2.svg
    - assets/vectors/group_11_x2.svg
    - assets/vectors/battery_5_x2.svg
    - assets/images/pngfuel_11.png
    - assets/images/pngfuel_141.png
    - assets/vectors/vector_19_x2.svg
    - assets/vectors/vector_36_x2.svg
    - assets/vectors/group_6846_x2.svg
    - assets/vectors/cellular_connection_x2.svg
    - assets/vectors/vector_18_x2.svg
    - assets/vectors/battery_x2.svg
    - assets/vectors/wifi_5_x2.svg
    - assets/vectors/vector_1_x2.svg
    - assets/vectors/vector_2_x2.svg
    - assets/images/image.jpeg
    - assets/vectors/group_x2.svg
    - assets/images/tree_top_juice_apple_grape_64_oz_1.png
    - assets/images/pngfuel_141.png
    - assets/images/pngfuel_14.png
    - assets/images/pngfuel_11.png
    - assets/images/tree_top_juice_apple_grape_64_oz_11.png
    - assets/images/pngfuel_13.png
    - assets/vectors/vector_3_x2.svg
    - assets/vectors/vector_31_x2.svg
    - assets/vectors/vector_21_x2.svg
    - assets/vectors/wifi_1_x2.svg
    - assets/vectors/vector_14_x2.svg
    - assets/vectors/vector_15_x2.svg
    - assets/vectors/vector_52_x2.svg
    - assets/vectors/battery_3_x2.svg
    - assets/vectors/cellular_connection_1_x2.svg
    - assets/vectors/vector_33_x2.svg
    - assets/vectors/vector_28_x2.svg
    - assets/images/pngfuel_3.png
    - assets/images/f_1_ea_7_dcce_3_b_5_d_06_cd_1_b_1418_f_9_b_941331.png
    - assets/images/pngfuel_16.png
    - assets/images/f_1_ea_7_dcce_3_b_5_d_06_cd_1_b_1418_f_9_b_94133.png
    - assets/vectors/vector_40_x2.svg
    - assets/vectors/vector_34_x2.svg
    - assets/vectors/cellular_connection_2_x2.svg
    - assets/vectors/vector_24_x2.svg
    - assets/vectors/vector_13_x2.svg
    - assets/vectors/wifi_3_x2.svg
    - assets/vectors/group_68622_x2.svg
    - assets/vectors/group_6862_x2.svg
    - assets/vectors/group_68625_x2.svg
    - assets/vectors/battery_4_x2.svg
    - assets/vectors/vector_38_x2.svg
    - assets/vectors/vector_25_x2.svg
    - assets/vectors/group_68621_x2.svg
    - assets/vectors/vector_20_x2.svg
    - assets/vectors/group_68461_x2.svg
    - assets/vectors/vector_41_x2.svg
    - assets/vectors/vector_4_x2.svg
    - assets/vectors/vector_17_x2.svg
    - assets/vectors/vector_49_x2.svg
    - assets/vectors/card_x2.svg
    - assets/vectors/vector_32_x2.svg
    - assets/vectors/vector_30_x2.svg
    - assets/vectors/vector_23_x2.svg
    - assets/vectors/vector_11_x2.svg
    - assets/vectors/vector_16_x2.svg
    - assets/vectors/vector_42_x2.svg
    - assets/images/main_1.jpeg
    - assets/vectors/group_6872_x2.svg
    - assets/images/f_1_ea_7_dcce_3_b_5_d_06_cd_1_b_1418_f_9_b_941331.png
    - assets/images/pngfuel_3.png
    - assets/images/f_1_ea_7_dcce_3_b_5_d_06_cd_1_b_1418_f_9_b_94133.png
    - assets/images/pngfuel_16.png
    - assets/vectors/vector_35_x2.svg
    - assets/vectors/cellular_connection_4_x2.svg
    - assets/vectors/vector_39_x2.svg
    - assets/vectors/vector_8_x2.svg
    - assets/vectors/wifi_2_x2.svg
    - assets/vectors/vector_6_x2.svg
    - assets/vectors/vector_10_x2.svg
    - assets/vectors/vector_x2.svg
    - assets/vectors/group_68626_x2.svg
    - assets/vectors/vector_26_x2.svg
    - assets/vectors/group_68623_x2.svg
    - assets/vectors/vector_47_x2.svg
    - assets/vectors/vector_44_x2.svg
    - assets/vectors/group_68627_x2.svg
    - assets/vectors/vector_7_x2.svg
    - assets/vectors/vector_29_x2.svg
    - assets/vectors/battery_2_x2.svg
    - assets/vectors/vector_45_x2.svg
    - assets/vectors/group_68624_x2.svg
    - assets/vectors/vector_12_x2.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
